version: "3.9"
volumes:
  your_name:

services:
  db_for_rally:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - your_name:/var/lib/postgresql/data
    ports:
      -